# If you run cracked you will want to disable this as running in offline mode causes this feature to hang on start up depending on your total logged players. (Bukkit api doesn't support offline mode)
automatic-head-cache: true

# Allow for labyrinth to register its default region services manager implementation on startup.
region-service-impl: false

# The amount of ticks it takes for an interactive component to become in-active (If you experience Unknown command errors a-lot you may want to bump this up some.)
interactive-component-removal: 200
