#
#
#  MMP""MM""YMM `7MMF'  `7MMF'`7MM"""YMM        .g8"""bgd   .g8""8q. `7MM"""Mq.  `7MM"""YMM
#  P'   MM   `7   MM      MM    MM    `7      .dP'     `M .dP'    `YM. MM   `MM.   MM    `7
#       MM        MM      MM    MM   d        dM'       ` dM'      `MM MM   ,M9    MM   d
#       MM        MMmmmmmmMM    MMmmMM        MM          MM        MM MMmmdM9     MMmmMM
#       MM        MM      MM    MM   Y  ,     MM.         MM.      ,MP MM  YM.     MM   Y  ,
#       MM        MM      MM    MM     ,M     `Mb.     ,' `Mb.    ,dP' MM   `Mb.   MM     ,M
#     .JMML.    .JMML.  .JMML..JMMmmmmMMM       `"bmmmd'    `"bmmd"' .JMML. .JMM..JMMmmmmMMM
#
# ============================================================================================
# Use the default Labyrinth GUI event listener? (Recommended 'true' by default)
use-click-event: true
# ============================================================================================